# Generated by Django 3.1.3 on 2020-11-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201127_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='product-test-1'),
            preserve_default=False,
        ),
    ]
