# Generated by Django 3.1.4 on 2020-12-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cupon',
            new_name='Coupon',
        ),
    ]
